apps/employees/urls.py
from django.urls import path
from .views import EmployeeList, EmployeeUpdate, EmployeeDelete, EmployeeCreate


urlpatterns = [
	path('create/', EmployeeCreate.as_view(), name='employee_create'),
	path('', EmployeeList.as_view(), name='employee_list'),
	path('update/<int:pk>/', EmployeeUpdate.as_view(), name='employee_update'),
	path('delete/<int:pk>/', EmployeeDelete.as_view(), name='employee_delete'),
]

management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('', include('apps.core.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
	path('funcionarios/', include('apps.employees.urls')),
	path('empresa/', include('apps.companies.urls')),
	path('colaboradores/', include('apps.departments.urls')),
	path('documentos/', include('apps.documents.urls')),
	path('hora-extra/', include('apps.overtime_record.urls')),
	path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documents/models.py
from django.db import models
from django.urls import reverse
from apps.employees.models import Employee


class Documents(models.Model):
	REASONS_CHOICES = (
	('ct', 'Carteira de trabalho'),
	('cm', 'Carteira de motorista'),
	('ot', 'Outros'),
	)
	
	description = models.CharField(max_length=70, verbose_name="Descrição",
	                               help_text="Descrição do documento, caso preciso")
	document_type = models.CharField(max_length=3, verbose_name="Tipo do documento",
	                                 choices=REASONS_CHOICES, default="ct")
	file  = models.FileField(upload_to="documents/")
	created_at = models.DateTimeField(auto_now_add=True)
	modified_at = models.DateTimeField(auto_now=True)

	# Relationships
	employee = models.ForeignKey(Employee, on_delete=models.PROTECT, verbose_name="Colaborador")

	class Meta:
		ordering = ['created_at']
		verbose_name = "Documento"
		verbose_name_plural = "Documentos"

	def __str__(self):
		return self.description

	def get_absolute_url(self):
		return reverse('employee_update', args=[self.employee.id])

apps/employees/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from apps.departments.models import Departments
from apps.companies.models import Enterprise


class Employee(models.Model):
	name = models.CharField(max_length=70, verbose_name="Nome", help_text="Nome do colaborador", unique=True)
	email = models.CharField(max_length=80, verbose_name="E-mail", help_text="E-mail de contato")
	phone = models.CharField(max_length=15, verbose_name="Telefone", help_text="Telefone de contato")
	created_at = models.DateTimeField(auto_now_add=True)
	modified_at = models.DateTimeField(auto_now=True)

	# Relationships
	user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Usuário")
	departments = models.ManyToManyField(Departments, verbose_name="Departamentos")
	enterprise = models.ForeignKey(Enterprise, on_delete=models.PROTECT, verbose_name="Empresa")

	class Meta:
		ordering = ['name']
		verbose_name = "Colaborador"
		verbose_name_plural = "Colaboradores"

	def get_absolute_url(self):
		return reverse('employee_list')
	
	@property
	def total_hours(self):
		total = self.overtimerecord_set.all().aggregate(models.Sum('hours'))['hours__sum']
		return total

	def __str__(self):
		return self.name

apps/overtime_record/models.py
from django.db import models
from django.urls import reverse
from apps.employees.models import Employee


class OvertimeRecord(models.Model):
	reason = models.CharField(max_length=100, verbose_name="Motivo", help_text="Qual o motivo para a hora extra?")
	hours = models.CharField(max_length=5, verbose_name="Horas trabalhadas", help_text="Quantidade de horas trabalhadas?")
	created_at = models.DateTimeField(auto_now_add=True)
	modified_at = models.DateTimeField(auto_now=True)

	# Relationships
	employee = models.ForeignKey(Employee, on_delete=models.PROTECT, verbose_name="Colaborador", null=True)

	class Meta:
		ordering = ['created_at', 'hours']
		verbose_name = "Hora extra"
		verbose_name_plural = "Hora extra"

	def __str__(self):
		return self.reason
	
	def get_absolute_url(self):
		#return reverse('overtime_record_update', args=[self.id])
		return reverse('employee_update', args=[self.employee.id])

apps/employees/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from .models import Employee
from django.contrib.auth.models import User


class EmployeeCreate(CreateView):
	model = Employee
	fields = ['name', 'departments', 'email', 'phone']

	def form_valid(self, form):
		user = self.request.POST['name'].lower().replace(' ', '_')
		employee = form.save(commit=False)
		employee.enterprise = self.request.user.employee.enterprise
		employee.user = User.objects.create(username=user)
		employee.save()
		messages.success(self.request, "{} criado com sucesso!".format(employee.user))
		return super(EmployeeCreate, self).form_valid(form)

class EmployeeList(ListView):
	model = Employee
	paginate_by = 10
	
	def get_queryset(self):
		employee_looged = self.request.user.employee.enterprise
		return Employee.objects.filter(enterprise=employee_looged)

class EmployeeUpdate(UpdateView):
	model = Employee
	fields = ['name', 'email', 'phone']

class EmployeeDelete(DeleteView):
	model = Employee
	success_url = reverse_lazy('employee_list')

apps/employees/templates/employees/employee_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
	<h1>'Você tem certeza que deseja excluir este colaborador?'</h1>
	<form method="post">
		{% csrf_token %}
		{{ form}}
		<button type="submit" class="btn btn-danger">Confirmar</button>
	</form>
{% endblock %}

apps/employees/templates/employees/employee_form.html
{% extends 'base.html' %}

{% block main %}
	<h1>Editar dados do colaborador</h1>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Salvar</button>
		<a href="{% url 'employee_list' %}" class="btn btn-info">Voltar</a>
	</form>
	<br>

	<h2>Documentos</h2>
	{% for document in object.documents_set.all %}
		<a href="{{ document.file.url }}">{{ document }}</a><br>
	{% endfor %}
	<br>
	{% if object %}
	<a href="{% url 'document_create' object.id %}" class="btn btn-success">
		Adicionar documento
	</a>
	{% endif %}
	<br><br>

	<h2>Horas extra</h2>
	{% for overtime_record in object.overtimerecord_set.all %}
		<li>
			<a href="{% url 'overtime_record_update' overtime_record.id %}">{{ overtime_record }} - {{ overtime_record.hours }}</a><br>
		</li>
	{% endfor %}

	{% if object %}
		<a href="{% url 'overtime_record_create' %}" class="btn btn-success">
			Adicionar hora extra
		</a>
	{% endif %}

	<h3>Total de horas extras: {{ object.total_hours }}</h3>
{% endblock %}

apps/employees/templates/employees/employee_list.html
{% extends 'base.html' %}

{% block main %}
	<h1>Lista de colaboradores</h1>
		<ul>
			{% for employee in object_list %}
					<a href="{% url 'employee_update' employee.id %}">{{ employee.name }}</a>  -   
					<a href="{% url 'employee_delete' employee.id %}">Excluir</a>
					<br>
				{% empty %}
					<li>Nenhum colaborador foi encontrado.</li>
			{% endfor %}
		</ul>

	<br>
	<a href="{% url 'employee_create' %}" class="btn btn-info">Adicionar colaborador</a>
{% endblock %}